site_name: Clawster Document
site_author: 'Chufan Chen'
repo_name: 'catwork-llc/clawster'
repo_url: 'https://github.com/Catwork-LLC/clawster'
theme:
  name: material
  custom_dir: 'docs/theme-override/'
nav:
  - Home: index.md
  - System: system.md
  - Jobs: jobs.md
  - Container: container.md
  - Module: module.md
  - Example: example.md
  - Slurm operations: slurm_operations.md
  - Slurm installation: slurm_installation.md


markdown_extensions:
    - attr_list
    - md_in_html
    - admonition
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.superfences 
    - footnotes
    - def_list
    - meta
    - toc:
        permalink: true
    - pymdownx.arithmatex
    - pymdownx.betterem:
        smart_enable: all
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde

extra:
  pagetime: 'on'
  alternate:
    - name: English
      link: ./en/
      lang: en
    - name: Chinese
      link: ./zh/
      lang: zh
plugins:
  - search:
      lang: 
        - en
        - zh
  - git-authors:
      show_contribution: true
      show_line_count: true
      fallback_to_empty: false
  - i18n:
      default_language: !ENV [DEFAULT_LANGUAGE, "en"]
      default_language_only: !ENV [DEFAULT_LANGUAGE_ONLY, false]
      docs_structure: suffix
      languages:
        default:
          name: Default (en)
          build: true
        en:
          name: English
          build: true
          site_name: "Clawster Document"
        zh:
          name: Chinese
          build: true
          site_name: "Clawster 文档"
      nav_translations:
        zh:
          Jobs: 作业
          System: 系统
          Container: 容器
          Module: 软件模块
  - git-revision-date-localized:
      fallback_to_build_date: true

